ZOOM_ENTER_STABLE_FRAMES = 8
ZOOM_CONTINUOUS_THRESHOLD = 10
ZOOM_LOST_TOLERANCE_FRAMES = 10

POINTER_LOST_TOLERANCE_FRAMES = 10
NAV_LOST_TOLERANCE_FRAMES = 12
PAN_LOST_TOLERANCE_FRAMES = 12

CLICK_COOLDOWN_FRAMES = 10
CLICK_FLASH_FRAMES = 8

TEST_BOX_BASE_SIZE = 180
TEST_BOX_MIN_SIZE = 100
TEST_BOX_MAX_SIZE = 340

INDEX_TIP_MARKER_RADIUS = 6

POINTER_DIRECT_SMOOTHING = 0.50
POINTER_SNAP_DISTANCE = 22

MOUSE_POINTER_SMOOTHING = 0.35
MOUSE_POINTER_SNAP_DISTANCE = 60

PAN_SCALE_X = 1.60
PAN_SCALE_Y = 1.60
PAN_DEADZONE = 2

SCROLL_STEP = 120
SCROLL_COOLDOWN_FRAMES = 2

DWELL_RADIUS_PIXELS = 12
DWELL_FRAMES_REQUIRED = 21

MODE_NONE = "NONE"
MODE_ZOOM = "ZOOM"
MODE_POINTER = "POINTER"
MODE_NAV = "NAV"
MODE_PAN = "PAN"